### ISSUE TITLE
rack-insight fails in Sinatra

### ISSUE THREAD

**Issue by javierhonduco** [pboling/rack-insight#37]
Running rack-insight as a Sinatra middleware yields the following error:
```
undefined method `present?' for body
file: enable-button.rb location: call line: 16
```
Wondering if I'm doing something wrong or if it's a bug.
Cheers,

**Comment by pboling** [comment]
Sounds like a bug.  If `present` is a rails ism and it should be removed from the code.  I think it is.  Oops.

**Comment by javierhonduco** [comment]
Do you think that ```unless body.empty? or body.nil?``` would do the trick?

**Comment by pboling** [comment]
Should be a very simple PR if you want to try.  Otherwise I'll try to get to is.  Just grep the code for `.present?`

**Comment by pboling** [comment]
@Javier yes!

**Comment by pboling** [comment]
But you need to check nil first, then check empty, because nil does not respond to empty.

**Comment by pboling** [comment]
Released 0.5.30 with this fix.

**Comment by jlecour** [comment]
On a Rails 4.2.0 app, I get this : 

    undefined method `empty?' for #<ActionDispatch::Response::RackBody:0x0000011158e578>

Is it related ?

**Comment by pboling** [comment]
@jlecour 
Oh, interesting.  I had someone else reporting an `empty?` bug as well.  No, it's not related to this bug.  Apparently what worked in Rails 3, and I think 4.0, no longer works in 4.2 in the Middleware.  This should be a new issue.
